name: numinous-treasury
author: alyphen
version: @version@
main: net.arvandor.numinoustreasury.NuminousTreasury
api-version: '1.19'
depend:
- rpk-core-bukkit
- rpk-player-lib-bukkit
- rpk-character-lib-bukkit
- rpk-notification-lib-bukkit
softdepend:
- Votifier
commands:
  profession:
    description: |
      Profession management command
      /profession set [profession] - Sets your profession
      /profession view - Show your profession info
      /profession list - View a list of professions
    usage: /<command> [set|view|list]
  numinousitem:
    description: Creates a numinous item
    usage: /<command> [item] (amount)
    aliases: [nitem]
  stamina:
    description: |
      Stamina management command
      /stamina view (player) - Views stamina
      /stamina set (player) [stamina] - Sets stamina
    usage: /<command> [set|view]
  node:
    description: |
      Node management command
      /node create - Starts the node creation wizard
      /node delete [node] - Deletes a node
      /node session set - Sets an attribute of the current node session
      /node session create - Finalizes the node creation session and creates the node
    usage: /<command> [create|delete|session]
  numinouslog:
    description: |
      Numinous log management command
      /numinouslog view - Views the item's log for the item in your hand
      /numinouslog add - Adds a new entry to the item's log for the item in your hand
    usage: /<command> [view|add]
    aliases: [nlog]
  booktitle:
    description: Sets a book's title, allowing breaking the character limit
    usage: /<command> [title]
    aliases: [btitle]
permissions:
  numinoustreasury.command.numinousitem:
    description: Allows creating items
    default: op
  numinoustreasury.command.stamina.set:
    description: Allows setting stamina
    default: op
  numinoustreasury.command.stamina.set.other:
    description: Allows setting stamina for other players
    default: op
  numinoustreasury.command.stamina.view:
    description: Allows viewing stamina
    default: true
  numinoustreasury.command.stamina.view.other:
    description: Allows viewing stamina for other players
    default: op
  numinoustreasury.command.stamina.view.precise:
    description: Allows viewing precise stamina numbers
    default: op
  numinoustreasury.command.node.create:
    description: Allows creating nodes
    default: op
  numinoustreasury.command.node.delete:
    description: Allows deleting nodes
    default: op
  numinoustreasury.command.numinouslog.add:
    description: Allows adding log entries
    default: op
  numinoustreasury.command.numinouslog.view:
    description: Allows viewing an item's log
    default: true
  numinoustreasury.command.profession.experience.add:
    description: Allows adding profession experience
    default: op
  numinoustreasury.command.profession.experience.set:
    description: Allows setting profession experience
    default: op
